"""Phase 17: Verify SE commands actually execute without errors.

Uses mound.fe (simplest example) to test each SE command category.
This validates that the commands generated by evolution_scripts.py
are accepted and executed by the SE binary, not just syntactically correct.
"""

import shutil
import subprocess
from pathlib import Path

import pytest

from kse.solver.evolution_scripts import (
    EvolutionStrategy,
    generate_evolution_script,
    generate_runtime_commands,
    _apply_preset,
)

from .conftest import EVOLVER_PATH, EXAMPLES_DIR


@pytest.fixture
def evolver(evolver_path):
    """Return the validated evolver path."""
    return evolver_path


@pytest.fixture
def mound_fe(tmp_path):
    """Copy mound.fe to temp directory and return path."""
    src = EXAMPLES_DIR / "basic" / "mound.fe"
    if not src.exists():
        pytest.skip("mound.fe not found")
    dst = tmp_path / "mound.fe"
    shutil.copy(src, dst)
    return dst


def _run_se_with_script(evolver, fe_path, script_text, runtime_cmds, timeout=120):
    """Inject a custom evolution script into a .fe file and run SE.

    Appends the script_text at the end of the .fe file (before any existing
    read commands), then pipes runtime_cmds to SE stdin.

    Returns (success: bool, stdout: str, stderr: str).
    """
    # Append script to .fe file
    original = fe_path.read_text()
    # Remove any existing gogo/gomore definitions to avoid conflict
    lines = original.split("\n")
    filtered = []
    skip_block = False
    for line in lines:
        # Skip existing macro definitions
        if any(line.strip().startswith(m) for m in ["gogo :=", "gomore :=", "gofine :=", "analyze :="]):
            skip_block = True
        if skip_block:
            if "}" in line:
                skip_block = False
            continue
        filtered.append(line)

    new_content = "\n".join(filtered) + "\n\n" + script_text + "\n"
    fe_path.write_text(new_content)

    dmp_name = fe_path.stem + ".dmp"

    try:
        proc = subprocess.run(
            [str(evolver), "-p1", fe_path.name],
            input=runtime_cmds,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=str(fe_path.parent),
        )
    except subprocess.TimeoutExpired:
        return False, "", "Timeout"

    dmp_exists = (fe_path.parent / dmp_name).exists()
    success = proc.returncode == 0 and dmp_exists

    return success, proc.stdout, proc.stderr


class TestSECommandExecution:
    """Verify individual SE commands execute without errors."""

    def test_basic_preset(self, evolver, mound_fe):
        """Basic preset: u, g, r, hessian."""
        s = EvolutionStrategy(preset="basic", n_refine=2, n_gradient=5, n_hessian=2)
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"Basic preset failed.\nstdout: {stdout[-300:]}\nstderr: {stderr[-300:]}"

    def test_standard_preset_with_gofine(self, evolver, mound_fe):
        """Standard preset: + V, u, gofine."""
        s = EvolutionStrategy(preset="standard", n_refine=2, n_gradient=5)
        s = _apply_preset(s)
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"Standard preset failed.\nstdout: {stdout[-300:]}\nstderr: {stderr[-300:]}"

    def test_hessian_seek(self, evolver, mound_fe):
        """hessian_seek command (hessian with line search)."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            use_hessian=False,
            use_hessian_seek=True,
            n_hessian=2,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"hessian_seek failed.\nstderr: {stderr[-300:]}"

    def test_conj_grad(self, evolver, mound_fe):
        """Conjugate gradient toggle (U command)."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            conj_grad=True,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"conj_grad failed.\nstderr: {stderr[-300:]}"

    def test_saddle(self, evolver, mound_fe):
        """saddle command (saddle point detection)."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            use_saddle=True,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"saddle failed.\nstderr: {stderr[-300:]}"

    def test_mesh_cleanup_commands(self, evolver, mound_fe):
        """Mesh quality: K (skinny), o (pop), edgeswap."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            use_skinny_refine=True,
            use_pop=True,
            use_edgeswap=True,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"Mesh cleanup failed.\nstderr: {stderr[-300:]}"

    def test_pop_edge_and_notch(self, evolver, mound_fe):
        """O (pop edge) and n (notch) commands."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            use_pop_edge=True,
            use_notch=True,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"pop_edge/notch failed.\nstderr: {stderr[-300:]}"

    def test_jiggle(self, evolver, mound_fe):
        """j (jiggle: random vertex perturbation)."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            use_jiggle=True,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"jiggle failed.\nstderr: {stderr[-300:]}"

    def test_tiny_edge_and_weed(self, evolver, mound_fe):
        """t (tiny edge) and w (weed) commands."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            tiny_edge_threshold=0.001,
            weed_threshold=1e-6,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"tiny_edge/weed failed.\nstderr: {stderr[-300:]}"

    def test_long_edge(self, evolver, mound_fe):
        """l (long edge subdivision) command."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            long_edge_threshold=0.5,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"long_edge failed.\nstderr: {stderr[-300:]}"

    def test_eigenprobe(self, evolver, mound_fe):
        """eigenprobe command (stability analysis)."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            eigenprobe=True,
            eigenprobe_value=0.0,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"eigenprobe failed.\nstderr: {stderr[-300:]}"

    def test_report_volumes_and_energy(self, evolver, mound_fe):
        """v (volume report) and print total_energy."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            report_volumes=True,
            report_energy=True,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"report failed.\nstderr: {stderr[-300:]}"

    def test_autopop_toggle(self, evolver, mound_fe):
        """autopop ON toggle."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            autopop=True,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"autopop failed.\nstderr: {stderr[-300:]}"

    def test_runge_kutta(self, evolver, mound_fe):
        """runge_kutta ON toggle."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            runge_kutta=True,
            use_hessian=False,  # RK is for gradient descent only
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"runge_kutta failed.\nstderr: {stderr[-300:]}"

    def test_normal_motion(self, evolver, mound_fe):
        """normal_motion ON toggle."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            normal_motion=True,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"normal_motion failed.\nstderr: {stderr[-300:]}"

    def test_scale_factor(self, evolver, mound_fe):
        """Fixed scale factor (m command)."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            scale_factor=0.1,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"scale_factor failed.\nstderr: {stderr[-300:]}"

    def test_gravity_toggle(self, evolver, mound_fe):
        """Explicit gravity G ON/OFF."""
        for grav_val in [True, False]:
            s = EvolutionStrategy(
                preset="basic",
                n_refine=2, n_gradient=5,
                gravity_on=grav_val,
            )
            script = generate_evolution_script(s)
            cmds = generate_runtime_commands(s, "mound.dmp")

            # Reset mound.fe for each test
            src = EXAMPLES_DIR / "basic" / "mound.fe"
            dst = mound_fe
            shutil.copy(src, dst)

            success, stdout, stderr = _run_se_with_script(evolver, dst, script, cmds)
            assert success, f"gravity_on={grav_val} failed.\nstderr: {stderr[-300:]}"


class TestAdvancedPresetIntegration:
    """Test complete advanced preset pipeline end-to-end."""

    def test_advanced_preset_full_pipeline(self, evolver, mound_fe):
        """Run advanced preset on mound.fe: all features active."""
        s = EvolutionStrategy(preset="advanced", n_refine=2, n_gradient=5)
        s = _apply_preset(s)
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"Advanced preset failed.\nstdout: {stdout[-500:]}\nstderr: {stderr[-500:]}"

        # Verify energy is reasonable
        dmp_path = mound_fe.parent / "mound.dmp"
        assert dmp_path.exists(), "No dump file produced"

    def test_custom_preset(self, evolver, mound_fe):
        """Custom preset with user-provided commands."""
        s = EvolutionStrategy(
            preset="custom",
            custom_commands=(
                "gogo := {\n"
                "  u; g 5;\n"
                "  r; u; g 5;\n"
                "  hessian;\n"
                "}\n"
                "gomore := {\n"
                "  g 5; hessian;\n"
                "}"
            ),
        )
        script = generate_evolution_script(s)
        cmds = "gogo;\ngomore;\ndump \"mound.dmp\";\nq\n"

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"Custom preset failed.\nstderr: {stderr[-300:]}"

    def test_selective_refine(self, evolver, mound_fe):
        """Selective refinement based on edge length."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            target_edge_length=0.3,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"Selective refine failed.\nstderr: {stderr[-300:]}"

    def test_all_mesh_commands_combined(self, evolver, mound_fe):
        """All mesh quality commands together."""
        s = EvolutionStrategy(
            preset="basic",
            n_refine=2, n_gradient=5,
            tiny_edge_threshold=0.001,
            long_edge_threshold=0.5,
            weed_threshold=1e-6,
            use_skinny_refine=True,
            use_pop=True,
            use_pop_edge=True,
            use_notch=True,
            use_edgeswap=True,
            use_jiggle=True,
        )
        script = generate_evolution_script(s)
        cmds = generate_runtime_commands(s, "mound.dmp")

        success, stdout, stderr = _run_se_with_script(evolver, mound_fe, script, cmds)
        assert success, f"All mesh commands failed.\nstderr: {stderr[-300:]}"
